site_name: 高考地理真题题库
site_url: https://yijia.uk
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
plugins:
  - search:
      lang: zh
  - tags:
      tags_file: tags.md
  - pagelist   # 添加这行来启用插件
nav:
  - 首页: index.md
  - 2022真题:
      - 全国甲卷: 2022/全国甲卷/index.md
      - 全国乙卷: 2022/全国乙卷/index.md
      - 山东卷: 2022/山东卷/index.md
      - 北京卷: 2022/北京卷/index.md
      - 天津卷: 2022/天津卷/index.md
      - 海南卷: 2022/海南卷/index.md
      - 辽宁卷: 2022/辽宁卷/index.md
      - 湖南卷: 2022/湖南卷/index.md
      - 江苏卷: 2022/江苏卷/index.md
      - 广东卷: 2022/广东卷/index.md
      - 湖北卷: 2022/湖北卷/index.md
      - 重庆卷: 2022/重庆卷/index.md
      - 河北卷: 2022/河北卷/index.md
      - 福建卷: 2022/福建卷/index.md
      - 浙江卷: 2022/浙江卷/index.md
      - 上海卷: 2022/上海卷/index.md
- 2023真题:
      - 全国甲卷: 2023/全国甲卷/index.md
      - 全国乙卷: 2023/全国乙卷/index.md
      - 新课标卷: 2023/新课标卷/index.md
      - 山东卷: 2023/山东卷/index.md
      - 湖南卷: 2023/湖南卷/index.md
      - 广东卷: 2023/广东卷/index.md
  - 2024真题:
      - 全国甲卷: 2024/全国甲卷/index.md
      - 全国乙卷: 2024/全国乙卷/index.md
      - 新课标卷: 2024/新课标卷/index.md
      - 山东卷: 2024/山东卷/index.md
      - 湖南卷: 2024/湖南卷/index.md
      - 广东卷: 2024/广东卷/index.md
  - 2025真题:
      - 全国甲卷: 2025/全国甲卷/index.md
      - 全国乙卷: 2025/全国乙卷/index.md
      - 新课标卷: 2025/新课标卷/index.md
      - 山东卷: 2025/山东卷/index.md
  - 题库分类:
      - 按知识点: tags.md
  - 关于本站: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true